name: upload-s3
on: workflow_dispatch
jobs:
  upload_web_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: "./frontend/build"
          DEST_PATH: "s3://${{ secrets.S3_BUCKET }}/"
          OPTIONS: "--delete --acl public-read --exclude 'README.md'"
